### ISSUE TITLE
Code error: duplicate property declaration

### ISSUE THREAD

**Issue by stijnbollen** [OrdnanceSurvey/leaflet-control-geocoder#3]
```
  var geocoders = Object.freeze({
    OSNamesAPI: OSNamesAPI,
    osNamesAPI: osNamesAPI,
    osPlacesAPI: OSPlacesAPI,
    osPlacesAPI: osPlacesAPI
  });
```
There's a duplicate property declaration in the geocoders object variable. The first `osPlacesAPI` property should be `OSPlacesAPI` instead.

**Comment by tmnnrs** [comment]
Fixed via [f51fcd8](https://github.com/OrdnanceSurvey/leaflet-control-geocoder/commit/f51fcd83ad9ed1521834a5dc0055b29f740c3539)
