### ISSUE TITLE
REAMDE.md: 404 on demo urls

### ISSUE THREAD

**Issue by stijnbollen** [OrdnanceSurvey/leaflet-control-geocoder#4]
Both demo urls [https://labs.os.uk/public/os-api-resources/leaflet-control-geocoder/os-names-api.html](https://labs.os.uk/public/os-api-resources/leaflet-control-geocoder/os-names-api.html) and [https://labs.os.uk/public/os-api-resources/leaflet-control-geocoder/os-places-api.html](https://labs.os.uk/public/os-api-resources/leaflet-control-geocoder/os-places-api.html) in [README.md](https://github.com/OrdnanceSurvey/leaflet-control-geocoder/blob/main/README.md) return a '404 Not Found' error page.

**Comment by tmnnrs** [comment]
Fixed via [f51fcd8](https://github.com/OrdnanceSurvey/leaflet-control-geocoder/commit/f51fcd83ad9ed1521834a5dc0055b29f740c3539)
